version: '2'

services:
  btc:
    container_name: btc-service
    build: ./btc/
    ports:
      - "7416:7416"
      - "7316:7316"
      - "7317:7317"
      - "7424:7424"
      - "4444:4444"
      - "8080:8080"
      - "8081:8081"
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - zookeeper
      - mysql
      - kafka
      - redis_sentinel
      - redis_slave
      - redis_master
    links:
      - zookeeper:zk
      - mysql:db
      - kafka
      - redis_sentinel
      - redis_slave
      - redis_master

  redis_master:
    container_name: btc-redis-master
    image: redis:4.0.2-alpine
    ports:
      - "6379:6379"

  redis_slave:
    container_name: btc-redis-slave
    image: redis:4.0.2-alpine
    ports:
      - "16380:6379"

  redis_sentinel:
    container_name: btc-redis-sentinel
    build: redis
    image: redis-sentinel
    environment:
      - MASTER_NAME=mymaster
      - QUORUM=1
      - MASTER=redis_master
      - SLAVES=redis_slave
    depends_on:
      - redis_master
      - redis_slave
    ports:
      - "26379:26379"

  mysql:
    container_name: btc-mysql
    build: ./db/
    ports:
      - "3306:3306"

  zookeeper:
    container_name: btc-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: btc-kafka
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
